# This file is a template, and might need editing before it works on your project.
# This example is for testing Django with MySQL.
#
# The test CI/CD variables MYSQL_DB, MYSQL_USER and MYSQL_PASS can be set in the project settings at:
#     Settings --> CI/CD --> Variables
#
# The Django settings in settings.py, used in tests, might look similar to:
#
#  DATABASES = {
#      'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': os.environ.get('MYSQL_DATABASE'),
#        	'USER':  os.environ.get('MYSQL_USER'),
#        	'PASSWORD': os.environ.get('MYSQL_PASSWORD'),
#       	'HOST': 'mysql',
#     	  'PORT': '3306',
#         'CONN_MAX_AGE':60,
#      },
#  }
#
# It is possible to use '--settings' to specify a custom settings file on the command line below or use an environment
# variable to trigger an include on the bottom of your settings.py:
#   if os.environ.get('DJANGO_CONFIG')=='test':
#       from .settings_test import *
#
# It is also possible to hardcode the database name and credentials in the settings.py file and in the .gitlab-ci.yml file.
#
# The mysql service needs some variables too. See https://hub.docker.com/_/mysql for possible mysql env variables
# Note that when using a service in GitLab CI/CD that needs environment variables to run, only variables defined in
# .gitlab-ci.yml are passed to the service and variables defined in the GitLab UI are not.
# https://gitlab.com/gitlab-org/gitlab/-/issues/30178
stages:
  - build
  - test
  - publish
  - deploy

variables:
  # DJANGO_CONFIG: "test"
  MYSQL_DATABASE: "db_name"
  MYSQL_ROOT_PASSWORD: "dbpass"
  MYSQL_USER: "username"
  MYSQL_PASSWORD: "dbpass"
  MYSQL_HOST: mysql

  # Deployment tags
  TAG_LATEST: albinoboi/sop:latest
  TAG_COMMIT: albinoboi/sop:$CI_COMMIT_SHORT_SHA

default:
  image: ubuntu:20.04

  cache:
    key: build-cache
    paths:
      - venv3.10/
      - ~/.cache/pip/
  #
  # Pick zero or more services to be used on all builds.
  # Only needed when using a docker container to run your tests in.
  # Check out: https://docs.gitlab.com/ee/ci/services/index.html
  services:
    - mysql:8.0
  #
  # This folder is cached between builds
  # http://docs.gitlab.com/ee/ci/yaml/README.html#cache
  before_script:
    - apt -y update
    - apt-get -yq install software-properties-common
    - add-apt-repository -y ppa:deadsnakes/ppa
    - apt -y install apt-utils
    - apt -y install net-tools python3.10 python3-pip mysql-client libmysqlclient-dev python3.10-distutils python3.10-dev
    - apt -y upgrade
    - "[ ! -d 'venv3.10' ] && pip3 install virtualenv && virtualenv venv3.10 -p python3.10"
    - ls
    - source venv3.10/bin/activate
    - pip3 install -r requirements.txt
    - pip3 install mysqlclient
    - pip3 install coverage
    - pip3 install -e backend_library/src
    - python3.10 -V

migrations:
  stage: build
  script:
    - source venv3.10/bin/activate
    - cd webserver/src/main/sop
    - python3.10 manage.py makemigrations --settings=sop.settings_ci
    # - python3 manage.py makemigrations myapp
    - python3.10 manage.py migrate --settings=sop.settings_ci
    - python3.10 manage.py showmigrations --settings=sop.settings_ci
    - python3.10 manage.py check --settings=sop.settings_ci


django-tests:
  stage: test
  script:
    - which python3.10
    - cd webserver/src/main/sop
    # The MYSQL user only gets permissions for MYSQL_DB, so Django can't create a test database.
    - echo "GRANT ALL on *.* to '${MYSQL_USER}';"| mysql -u root --password="${MYSQL_ROOT_PASSWORD}" -h mysql
    # use python3 explicitly. see https://wiki.ubuntu.com/Python/3
    - python3.10 manage.py showmigrations --settings=sop.settings_ci
    - python3.10 -m coverage run --source="." --omit="media/*","*/migrations/*","*/__init__.py","tests/*" manage.py test --settings sop.settings_ci
    - python3.10 -m coverage report


backend-tests:
  stage: test
  script:
    - which python3.10
    - cd backend_library/src
    - python3.10 -m coverage run --source=backend/ --omit="*/__init__.py" -m unittest discover -p "*.py" -s test/ -t .
    - python3.10 -m coverage report

publish-build:
  inherit:
    default: false
  stage: publish
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t $TAG_COMMIT -t $TAG_LATEST .
    - docker login -u $DOCKERHUB_USER -p $DOCKERHUB_TOKEN
    - docker push $TAG_COMMIT
    - docker push $TAG_LATEST

deploy-app:
  inherit:
    default: false
  stage: deploy
  image: alpine:latest
  tags:
    - deployment
  script:
    - chmod og= $ID_RSA
    - apk update && apk add openssh-client docker-compose
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "cd docker/sop"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker login -u $DOCKERHUB_USER -p $DOCKERHUB_TOKEN"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker-compose down"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker pull $TAG_COMMIT"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker-compose up -d"
  environment:
    name: development
    url: https://sop.ffhz.site
